# application: mimas-aotb
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Complete these enviornment variables with your own keys, urls and IDs
# app.yaml is checked into source code control and shared with others so
# it is not safe to keep these things here
# Rather create a app_live.yaml with your keys etc.
# Use app_live.yaml when deploying and in dev_appserver simulations
#
env_variables:
    SENDGRID_API_KEY: "secret send grid key"
    GAE_USE_SOCKETS_HTTPLIB : 'true'
    FIREBASE_apiKey: "semi secret Firebase api key"
    FIREBASE_authDomain: "some domain .firebaseapp.com"
    FIREBASE_databaseURL: "database .firebaseio.com"
    FIREBASE_projectId: "your firebase project id"
    FIREBASE_storageBucket: "firebase storage bucket .appspot.com"
    FIREBASE_messagingSenderId: "firebase sender ID"

automatic_scaling:
  max_instances: 1

# Handler order is important
# Caught me out more than once

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /dist
  static_dir: dist
  secure: always

- url: /static/privacy.html
  static_files: static/privacy.html
  upload: static/privacy.html
  secure: always

- url: .*
  script: main.app
  secure: always

builtins:
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: ssl
  version: latest
